In [1]:
import numpy as np  
import pandas as pd  
import random as rd  

In [2]:
df = pd.read_csv('datingTestSet.txt')


In [30]:
    fr = open('datingTestSet.txt')
    line_mat = fr.readlines()
    data_mat=[]
    for line in line_mat:
        line=line.strip()
        line_list = line.split('\t')
        data_mat.append([float(line_list[0]),float(line_list[1]),float(line_list[2])])

In [36]:
data_mat=np.array(data_mat)
data_mat[:,0]

array([ 40920.,  14488.,  26052.,  75136.,  38344.,  72993.,  35948.,
        42666.,  67497.,  35483.,  50242.,  63275.,   5569.,  51052.,
        77372.,  43673.,  61364.,  69673.,  15669.,  28488.,   6487.,
        37708.,  22620.,  28782.,  19739.,  36788.,   5741.,  28567.,
         6808.,  41611.,  36661.,  43605.,  15360.,  63796.,  10743.,
        70808.,  72011.,   5914.,  14851.,  33553.,  44952.,  17934.,
        27738.,  29290.,  42330.,  36429.,  39623.,  32404.,  27268.,
         5477.,  14254.,  68613.,  41539.,   7917.,  21331.,   8338.,
         5176.,  18983.,  68837.,  13438.,  48849.,  12285.,   7826.,
         5565.,  10346.,   1823.,   9744.,  16857.,  39336.,  65230.,
         2463.,  27353.,  16191.,  12258.,  42377.,  25607.,  77450.,
        58732.,  46426.,  32688.,  64890.,   8554.,  28861.,  42050.,
        32193.,  64895.,   2355.,      0.,  70406.,  57399.,  41732.,
        11429.,  75270.,   5459.,  73520.,  40279.,  21540.,  17694.,
        22329.,  465

In [37]:
BabyDataSet = list(zip((data_mat[:,0]),(data_mat[:,1]),(data_mat[:,2])))


In [38]:
df = pd.DataFrame(data = BabyDataSet)
                 
                  

In [40]:
    fr = open('datingTestSet.txt')
    line_mat = fr.readlines()
    data_mat=[]
    for line in line_mat:
        line=line.strip()
        line_list = line.split('\t')
        data_mat.append(line_list)
    data_mat=np.array(data_mat[:,0:3])
    pd_data_col = list(zip(data_mat[:,0],data_mat[:,1],data_mat[:,2]))
    label_mat = np.array(data_mat[:,-1])
    pd_label_col = list(zip(label_mat))
    df = pd.DataFrame(data =  pd_data_col)
    label = pd.DataFrame(data=pd_label_col)

TypeError: list indices must be integers, not tuple

In [42]:
    import csv
    file = open('datingTestSet.csv','wb') 
    my_save=csv.writer(file) 
    fr = open('datingTestSet.txt')
    line_mat = fr.readlines()
    data_mat=[]
    for line in line_mat:
        line=line.strip()
        line_list = line.split('\t')
        data_mat.append(line_list)
        my_save.writerow(line_list)
    file.close()

In [47]:
df=pd.read_csv('datingTestSet.csv',header=None)

In [55]:
df

0          1         2           3
0    40920   8.326976  0.953952  largeDoses
1    14488   7.153469  1.673904  smallDoses
2    26052   1.441871  0.805124   didntLike
3    75136  13.147394  0.428964   didntLike
4    38344   1.669788  0.134296   didntLike
5    72993  10.141740  1.032955   didntLike
6    35948   6.830792  1.213192  largeDoses
7    42666  13.276369  0.543880  largeDoses
8    67497   8.631577  0.749278   didntLike
9    35483  12.273169  1.508053  largeDoses
10   50242   3.723498  0.831917   didntLike
11   63275   8.385879  1.669485   didntLike
12    5569   4.875435  0.728658  smallDoses
13   51052   4.680098  0.625224   didntLike
14   77372  15.299570  0.331351   didntLike
15   43673   1.889461  0.191283   didntLike
16   61364   7.516754  1.269164   didntLike
17   69673  14.239195  0.261333   didntLike
18   15669   0.000000  1.250185  smallDoses
19   28488  10.528555  1.304844  largeDoses
20    6487   3.540265  0.822483  smallDoses
21   37708   2.991551  0.833920   didntLike
22   22620   5.297865  0.638306  smallDoses
23   28782   6.593803  0.187108  largeDoses
24   19739   2.816760  1.686209  smallDoses
25   36788  12.458258  0.649617  largeDoses
26    5741   0.000000  1.656418  smallDoses
27   28567   9.968648  0.731232  largeDoses
28    6808   1.364838  0.640103  smallDoses
29   41611   0.230453  1.151996   didntLike
..     ...        ...       ...         ...
970  53711  12.149747  1.389088  largeDoses
971  64371   9.149678  0.874905   didntLike
972   9289   9.666576  1.370330  smallDoses
973  60613   3.620110  0.287767   didntLike
974  18338   5.238800  1.253646  smallDoses
975  22845  14.715782  1.503758  largeDoses
976  74676  14.445740  1.211160   didntLike
977  34143  13.609528  0.364240  largeDoses
978  14153   3.141585  0.424280  smallDoses
979   9327   0.000000  0.120947  smallDoses
980  18991   0.454750  1.033280  smallDoses
981   9193   0.510310  0.016395  smallDoses
982   2285   3.864171  0.616349  smallDoses
983   9493   6.724021  0.563044  smallDoses
984   2371   4.289375  0.012563  smallDoses
985  13963   0.000000  1.437030  smallDoses
986   2299   3.733617  0.698269  smallDoses
987   5262   2.002589  1.380184  smallDoses
988   4659   2.502627  0.184223  smallDoses
989  17582   6.382129  0.876581  smallDoses
990  27750   8.546741  0.128706  largeDoses
991   9868   2.694977  0.432818  smallDoses
992  18333   3.951256  0.333300  smallDoses
993   3780   9.856183  0.329181  smallDoses
994  18190   2.068962  0.429927  smallDoses
995  11145   3.410627  0.631838  smallDoses
996  68846   9.974715  0.669787   didntLike
997  26575  10.650102  0.866627  largeDoses
998  48111   9.134528  0.728045  largeDoses
999  43757   7.882601  1.332446  largeDoses

[1000 rows x 4 columns]

In [51]:
from sklearn import preprocessing
X_train = np.array([[ 1., -1.,  3.],
                   [ 2.,  0.,  0.],
                   [ 0.,  1., -1.]])
min_max_scaler = preprocessing.MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)

In [80]:
df

f1         f2        f3       label  label_id
0    40920   8.326976  0.953952  largeDoses         0
1    14488   7.153469  1.673904  smallDoses         1
2    26052   1.441871  0.805124   didntLike         2
3    75136  13.147394  0.428964   didntLike         2
4    38344   1.669788  0.134296   didntLike         2
5    72993  10.141740  1.032955   didntLike         2
6    35948   6.830792  1.213192  largeDoses         0
7    42666  13.276369  0.543880  largeDoses         0
8    67497   8.631577  0.749278   didntLike         2
9    35483  12.273169  1.508053  largeDoses         0
10   50242   3.723498  0.831917   didntLike         2
11   63275   8.385879  1.669485   didntLike         2
12    5569   4.875435  0.728658  smallDoses         1
13   51052   4.680098  0.625224   didntLike         2
14   77372  15.299570  0.331351   didntLike         2
15   43673   1.889461  0.191283   didntLike         2
16   61364   7.516754  1.269164   didntLike         2
17   69673  14.239195  0.261333   didntLike         2
18   15669   0.000000  1.250185  smallDoses         1
19   28488  10.528555  1.304844  largeDoses         0
20    6487   3.540265  0.822483  smallDoses         1
21   37708   2.991551  0.833920   didntLike         2
22   22620   5.297865  0.638306  smallDoses         1
23   28782   6.593803  0.187108  largeDoses         0
24   19739   2.816760  1.686209  smallDoses         1
25   36788  12.458258  0.649617  largeDoses         0
26    5741   0.000000  1.656418  smallDoses         1
27   28567   9.968648  0.731232  largeDoses         0
28    6808   1.364838  0.640103  smallDoses         1
29   41611   0.230453  1.151996   didntLike         2
..     ...        ...       ...         ...       ...
970  53711  12.149747  1.389088  largeDoses         0
971  64371   9.149678  0.874905   didntLike         2
972   9289   9.666576  1.370330  smallDoses         1
973  60613   3.620110  0.287767   didntLike         2
974  18338   5.238800  1.253646  smallDoses         1
975  22845  14.715782  1.503758  largeDoses         0
976  74676  14.445740  1.211160   didntLike         2
977  34143  13.609528  0.364240  largeDoses         0
978  14153   3.141585  0.424280  smallDoses         1
979   9327   0.000000  0.120947  smallDoses         1
980  18991   0.454750  1.033280  smallDoses         1
981   9193   0.510310  0.016395  smallDoses         1
982   2285   3.864171  0.616349  smallDoses         1
983   9493   6.724021  0.563044  smallDoses         1
984   2371   4.289375  0.012563  smallDoses         1
985  13963   0.000000  1.437030  smallDoses         1
986   2299   3.733617  0.698269  smallDoses         1
987   5262   2.002589  1.380184  smallDoses         1
988   4659   2.502627  0.184223  smallDoses         1
989  17582   6.382129  0.876581  smallDoses         1
990  27750   8.546741  0.128706  largeDoses         0
991   9868   2.694977  0.432818  smallDoses         1
992  18333   3.951256  0.333300  smallDoses         1
993   3780   9.856183  0.329181  smallDoses         1
994  18190   2.068962  0.429927  smallDoses         1
995  11145   3.410627  0.631838  smallDoses         1
996  68846   9.974715  0.669787   didntLike         2
997  26575  10.650102  0.866627  largeDoses         0
998  48111   9.134528  0.728045  largeDoses         0
999  43757   7.882601  1.332446  largeDoses         0

[1000 rows x 5 columns]

In [57]:
df['label']=pd.factorize(df[3])[0]

In [63]:
df1=df.drop([3])

In [65]:
df.columns=['0','1','2','3','label']

In [70]:
df.columns

Index([u'0', u'1', u'2', u'3', u'label'], dtype='object')

In [73]:
 df=pd.read_csv('datingTestSet.csv',names=['f1','f2','f3','label'])

In [76]:
df['label_id']=pd.factorize(df['label'])[0]

In [84]:
df.drop(['label'],axis=1)

f1         f2        f3  label_id
0    40920   8.326976  0.953952         0
1    14488   7.153469  1.673904         1
2    26052   1.441871  0.805124         2
3    75136  13.147394  0.428964         2
4    38344   1.669788  0.134296         2
5    72993  10.141740  1.032955         2
6    35948   6.830792  1.213192         0
7    42666  13.276369  0.543880         0
8    67497   8.631577  0.749278         2
9    35483  12.273169  1.508053         0
10   50242   3.723498  0.831917         2
11   63275   8.385879  1.669485         2
12    5569   4.875435  0.728658         1
13   51052   4.680098  0.625224         2
14   77372  15.299570  0.331351         2
15   43673   1.889461  0.191283         2
16   61364   7.516754  1.269164         2
17   69673  14.239195  0.261333         2
18   15669   0.000000  1.250185         1
19   28488  10.528555  1.304844         0
20    6487   3.540265  0.822483         1
21   37708   2.991551  0.833920         2
22   22620   5.297865  0.638306         1
23   28782   6.593803  0.187108         0
24   19739   2.816760  1.686209         1
25   36788  12.458258  0.649617         0
26    5741   0.000000  1.656418         1
27   28567   9.968648  0.731232         0
28    6808   1.364838  0.640103         1
29   41611   0.230453  1.151996         2
..     ...        ...       ...       ...
970  53711  12.149747  1.389088         0
971  64371   9.149678  0.874905         2
972   9289   9.666576  1.370330         1
973  60613   3.620110  0.287767         2
974  18338   5.238800  1.253646         1
975  22845  14.715782  1.503758         0
976  74676  14.445740  1.211160         2
977  34143  13.609528  0.364240         0
978  14153   3.141585  0.424280         1
979   9327   0.000000  0.120947         1
980  18991   0.454750  1.033280         1
981   9193   0.510310  0.016395         1
982   2285   3.864171  0.616349         1
983   9493   6.724021  0.563044         1
984   2371   4.289375  0.012563         1
985  13963   0.000000  1.437030         1
986   2299   3.733617  0.698269         1
987   5262   2.002589  1.380184         1
988   4659   2.502627  0.184223         1
989  17582   6.382129  0.876581         1
990  27750   8.546741  0.128706         0
991   9868   2.694977  0.432818         1
992  18333   3.951256  0.333300         1
993   3780   9.856183  0.329181         1
994  18190   2.068962  0.429927         1
995  11145   3.410627  0.631838         1
996  68846   9.974715  0.669787         2
997  26575  10.650102  0.866627         0
998  48111   9.134528  0.728045         0
999  43757   7.882601  1.332446         0

[1000 rows x 4 columns]

In [85]:
    df=pd.read_csv('datingTestSet.csv',names=['f1','f2','f3','label'])
    df['label_id']=pd.factorize(df['label'])[0]
    df.drop(['label'],axis=1)

    data_mat = df.values
    train_data = data_mat[:,0:3]
    label = data_mat[:,-1]
    min_max_scaler = preprocessing.MinMaxScaler()
    feature = min_max_scaler.fit_transform(train_data)


e:\python27_64\lib\site-packages\sklearn\utils\validation.py:420: DataConversionWarning: Data with input dtype object was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [86]:
feature[:1]

array([[ 0.44832535,  0.39805139,  0.56233353]])

In [98]:
-



In [91]:
model = knn('datingTestSet')

In [102]:
model = knn('datingTestSet')
model.train()
x=[0.44832535,  0.39805139,  0.56233353];k=3
res=model.test(x,k)


e:\python27_64\lib\site-packages\sklearn\utils\validation.py:420: DataConversionWarning: Data with input dtype object was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [103]:
res

0

In [101]:
feature[0]

array([ 0.44832535,  0.39805139,  0.56233353])

In [104]:
label[0]

0

In [105]:
model.feature[0]

array([ 0.44832535,  0.39805139,  0.56233353])